owner: Liber-UFPE
repo: upptime

sites:
  - name: "Liber / Página Inicial"
    url: "http://www.liber.ufpe.br/"
  - name: "Liber / Monumenta Hyginia"
    url: "http://www.liber.ufpe.br/hyginia/"
  - name: "Liber / Visão Holandesa"
    url: "http://www.liber.ufpe.br/visao-holandesa/"
  - name: "Railway / Visão Holandesa"
    url: "https://visao-holandesa.up.railway.app/health"
  - name: "Railway / Monumenta Hyginia"
    url: "https://hyginia.up.railway.app/health"
  - name: "Liber / Memórias do Golpe"
    url: "http://www.liber.ufpe.br/tg/modules/busca/listar_projeto.php?cod=1"
  - name: "Liber / Memorial Joaquim Caetano"
    url: "http://www.liber.ufpe.br/jcaetano/modules/busca/listar_projeto.php?cod=2"
  - name: "Liber / Pereira da Costa"
    url: "http://www.liber.ufpe.br/pc2/processYear.jsp?query=1493"
  - name: "Liber / Selos"
    url: "http://www.liber.ufpe.br/selos/modules/home/listar_projeto.php?cod=1"
  - name: "Liber / Ultramar"
    url: "http://www.liber.ufpe.br/novoclio/?a=3"

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Liber Status
  introTitle: "**Liber Status**: status das aplicações do Liber"
  introMessage: Essa página mostra o status das aplicações mantidas pelo [Laboratório Liber](http://www.liber.ufpe.br/), se estão acessíveis para os usuários, e funcionando como esperado.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Liber-UFPE/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
